### ISSUE TITLE
Support for Raspberry Pi Pico RP2040

### ISSUE THREAD

**Issue by zpm1066** [mikalhart/TinyGPSPlus#103]
Thanks for the fantastic work on TinyGPSPlus.

Do you have plans to port TinyGPSPlus to the Raspberry Pi Pico RP2040? 

With the RP2040 gathering a lot of support over 4th last year, I and quite a few other folks would certainly like to see TinyGPSPlus support the Pico. 

Please consider. Thank you.

**Comment by cyberman54** [comment]
TinyGPSplus is a NMEA parser, written in C++, thus it's platform independent.So there is no need to port anything to a certain platform. Just use it as is in you C++ toolchain for your platform.

**Comment by zpm1066** [comment]
@cyberman54, Yes, of course! I have both u-blox Neo 6MN and 8MN working with Pico W. Thanks.

**Comment by mikalhart** [comment]
Great!  @zpm1066, did you have to modify anything to get it to work on the Pi?  (I worry about possible Arduino dependencies like the 'millis' function.  Haven't played with the Pi yet to understand its working environment.)

**Comment by zpm1066** [comment]
Hi @mikalhart, no. I used your TinyGPSPlus as is. Used Serial1 UART on the Raspberry Pico W.
Thank you for the great NMEA parser.
