### ISSUE TITLE
Update rate

### ISSUE THREAD

**Issue by iAsh347** [mikalhart/TinyGPSPlus#112]
How do I change the update rate when finding out the speed? I’m using a neo-6m and L80 gps module

**Comment by mikalhart** [comment]
Hi @iAsh347.  TinyGPS++ is only a library for parsing _input_ streams from GPS devices.  It is agnostic about the specific manufacturer and isn't designed to be able to configure them.  To do that you'd refer to your device's documentation and write some separate code that writes to the Serial port the GPS is attached to.  Clear?
