### ISSUE TITLE
Change update frequency

### ISSUE THREAD

**Issue by xt1at1n9** [mikalhart/TinyGPSPlus#14]
I want to change the update frequency without changing the baud-rate. I dont want to use delays. Anything to add in DeviceExample program or should I do some changes in the header file?

**Comment by mikalhart** [comment]
This library doesn't have any dependency or even any way to control or react to the device's update frequency.  It simply processes incoming NMEA characters as quickly or slowly as you care to feed them to it.  If your device has a mechanism to change its update frequency you would do this outside this library.  It's just a parser.
