### ISSUE TITLE
Module GPS GY-GPS6MV2

### ISSUE THREAD

**Issue by andressaluz** [mikalhart/TinyGPSPlus#18]

**Comment by andressaluz** [comment]
Hello, how are you ?
I have one question. You can help me?
I have one module gps and one arduino mega, however all sketch what use not function. It's lib (tinyGPSPlus) compatible with this gps (GY-GPS6MV2)?

Sorry, i don't speak/read in English.
Thanks.

**Comment by andressaluz** [comment]
my mail andressa.rtb@gmail.com

Please, help me. This project is work of university.

**Comment by mikalhart** [comment]
Yes, Andressa, if you have it operating in NMEA mode it should work.

**Comment by andressaluz** [comment]
You can help me ? with one sketch simple, what function.

**Comment by andressaluz** [comment]
our manual of use to the TinyGPS.
