### ISSUE TITLE
encode +CGNSINF

### ISSUE THREAD

**Issue by smb-soft** [mikalhart/TinyGPSPlus#24]
Hi 

how can i encode the +CGINF Message?

+CGNSINF:1,1,20150327014838.000,31.221783,121.354528,114.600,0.28,0.0,1,,1.9,2.2,1.0,,8,4,,,42,,

+CGNSINF: <GNSS run status>,<Fix status>,<UTC date & Time>,<Latitude>,<Longitude>,<MSL Altitude>,<Speed Over Ground>,<Course Over Ground>,<Fix Mode>,<Reserved1>,<HDOP>,<PDOP>,<VDOP>,<Reserved2>,<GNSS Satellites in View>,<GNSS Satellites Used>,<GLONASS SatellitesUsed>,<Reserved3>,<C/N0 max>,<HPA>,<VPA>

**Comment by mikalhart** [comment]
That's not an NMEA string, so TinyGPS++ doesn't parse it.  I'm afraid you'll have to use conventional parsing techniques to extract the various fields.  Look at the GPSStatus function in Adafruit's FONA library for example.
