### ISSUE TITLE
Number of Satellites and altitude

### ISSUE THREAD

**Issue by Hachmamut** [mikalhart/TinyGPSPlus#26]
I'm trying to get the number of used satellites and the altitude from my GPS modul, a ublox NEO 6M.

Reading the blank Serial data, I can see that both values a in the GPGGA Sentence.
But using the functions of your library results in "0" in both cases. Any idea what the problem is?
Best regards

Felix

**Comment by mikalhart** [comment]
Can you please post the GPGGA sentence and the code you are using (that returns the "0")?

**Comment by AEK-BKF** [comment]
Hi,

Any news about your issue ? I have the same mistake.

Thanks.

**Comment by AEK-BKF** [comment]
Hi,

Any news about your issue ? I have the same mistake.

Thanks.

**Comment by AEK-BKF** [comment]
Never mind, it works :) just wait for few moments :)

**Comment by Metaln00b** [comment]
It is still an issue.

Using `TinyGPSCustom customAltitude(gps, "GPGGA", 9);` and `TinyGPSCustom customSattelites(gps, "GPGGA", 7);` the value is empty, too. GPPGA shows both values with fix flag = 1.

Any solution?

**Comment by Metaln00b** [comment]
Setting the Baud to 9600 and set "protocol in" from "0+1+5 - UBX+NMEA+RTCM3" to "0+1 - UBX+NMEA" via u-center solves the problem.
