### ISSUE TITLE
Improper date output

### ISSUE THREAD

**Issue by stevieb9** [mikalhart/TinyGPSPlus#31]
No matter what I attempt, I can never get the date to be displayed correctly.

If I paste my own GPS data into the BasicExample, it outputs correctly. However, none of the other examples will output the date in any other format than day: 00, mon: 00 and year: 2000 when printing it manually using `gps.date.day()`, `month()` and `year()`.

I'm not proficient enough in C++ to understand where the parsing is occurring, or what is holding the date from being calculated in any program outside of Basic Example. All other information is displayed correctly while receiving data from my GPS unit live-time.

Here's a snip of my GPS data:

    "$GPRMC,180110.000,A,5111.1111,N,11411.1111,W,0.00,319.94,280517,,,D*75\r\n"
    "$GPGGA,180111.000,5111.1111,N,11411.1111,W,2,7,1.39,1099.1,M,-17.5,M,0000,0000*5D\r\n"
    "$GPRMC,180111.000,A,5111.1111,N,11411.1111,W,0.00,319.94,280517,,,D*74\r\n"
    "$GPGGA,180112.000,5111.1111,N,11411.1111,W,2,7,1.39,1099.1,M,-17.5,M,0000,0000*5E\r\n";

I've been fiddling with this for hours, and it's the only thing holding me back from being able to move forward.

Great piece of software otherwise though.

**Comment by mikalhart** [comment]
Is it possible you're not processing the incoming character stream fast enough?  This is quite common, especially with 5 or 10 Hz modules.  Check the .failedChecksum() counter to see if it's increasing.
