### ISSUE TITLE
Excample for Hardware Serial imput

### ISSUE THREAD

**Issue by bobybobybob** [mikalhart/TinyGPSPlus#36]
Example for Hardware Serial input is needed :-)

**Comment by mikalhart** [comment]
You are probably right.  Meanwhile, if it's unclear, simply remove all lines that declare the object:

`SoftwareSerial ss(RXPin, TXPin);`

Then, everywhere else replace "ss" with Serial2 or whatever your port's name is.

**Comment by bobybobybob** [comment]
Thank you :-)
