### ISSUE TITLE
Missing Feature

### ISSUE THREAD

**Issue by DOUG888** [mikalhart/TinyGPSPlus#42]
Addition of accessible values #4,6 and 11
This will give full use of available data and make display formatting easier.
Thanks
Doug
E.g: 
$ GPRMC, 033308.00, A, 3022.29739, N, 11454.04296, E, 0.044, 111116 ,,, A * 75

(1) UTC time, hhmmss (hours and seconds) 
(2) positioning state, A = effective positioning, V = invalid positioning 
(3) latitude ddmm.mmmmm (degrees) 
(4) latitude hemisphere N (northern hemisphere) or S (southern hemisphere) 
(5) longitude dddmm.mmmmm (degrees) 
(6) longitude hemisphere E (longitude) or W (west longitude) 
(7) The ground speed (000.0 to 999.9) 
(8) ground heading (000.0 ~ 359.9 degrees, with true north as the reference) 
(9) UTC date, ddmmyy (day month month) 
(10) magnetic declination (000.0 ~ 180.0 degrees, less than the leading digits complement 0) 
(11) Magnetic declination direction, E (east) or W (west) 
(12) Mode indication (A = autonomous positioning, D = differential, E = estimation, N = data invalid)

**Comment by mikalhart** [comment]
Hi @DOUG888.  For what it's worth #4 and #6 are implicitly present in the sign, i.e. negative latitudes and longitudes are S and W, respectively.  TinyGPS++ doesn't inherently provide magnetic declination, but you can get it with a TinyGPSCustom object.
