### ISSUE TITLE
CourseTo gives incorrect course

### ISSUE THREAD

**Issue by mat01** [mikalhart/TinyGPSPlus#44]
Does the TinyGPSPlus::courseTo method work properly? It gives me a course of 288.71 degrees, when the actual course seems to be about 301 degrees. The coords I'm using are : from (51.433,-0.3499) to (51.610875,-0.808697).

**Comment by mikalhart** [comment]
Hi @mat01,

I ran a simple test program that printed out the return value of courseTo using your provided values.  It printed 302.11, so I think the calculation is correct.
