### ISSUE TITLE
GPS data is not changing

### ISSUE THREAD

**Issue by pesengineeringclub** [mikalhart/TinyGPSPlus#45]
Hi 
First of all, thanks for the library. when we test it, the GPS data is not changing even we moving far away. Do you have any idea about the issue? thanks.

we use  Seeeduino LoRaWAN W/GPS
https://www.seeedstudio.com/Seeeduino-LoRaWAN-W%2FGPS-p-2781.html

**Comment by mikalhart** [comment]
Can you examine the raw NMEA code?  This library merely parses the raw NMEA.

**Comment by aliexclusive** [comment]
Hi

I got nice raw NMEA codes. 
![gps raw serial](https://user-images.githubusercontent.com/23704914/68143411-71949c80-ff42-11e9-8668-260bf79d97b5.jpeg)

But when I test DeviceExample, it returns the following error.

Location: INVALID  Date/Time: INVALID INVALID

**Comment by mikalhart** [comment]
Hi Muhammed—

 

If you’re printing the raw NMEA while processing them, you may have created a delay that causes overflow.  Also, check to make sure baud and port are correct in the program.
