### ISSUE TITLE
Cannot use 3D Speed

### ISSUE THREAD

**Issue by gtremb** [mikalhart/TinyGPSPlus#46]
Very new here and I might miss something...   Speed calculates only the speed over ground (2D). However, the librairy doesn't seems to allow to extract the 3D speed. Is there a way to switch to 3D speed? When reviewing documentation from U-Blox, it looks like it could be possible by changing filters.

**Comment by mikalhart** [comment]
This sounds like a job for a TinyGPSCustom object?
