### ISSUE TITLE
CustomFields sample does not work with NEO-M8N

### ISSUE THREAD

**Issue by Fbo06** [mikalhart/TinyGPSPlus#49]
Hello, can someone please tell me if this custom fields HDOP, VDOP work with a NEO-M8N ? thank you for your response.

**Comment by Eheran1** [comment]
The custom fields seem to have problems with "GN..." instead of "GP...".
NEO-M8Q here and GNGST as well as GNGNS custom values are not working, see the other issue(s).

**Comment by mikalhart** [comment]
I think this is a non-issue?  Can I close?

**Comment by johnjo90** [comment]
Ok thanks

2019년 1월 4일 (금) 오전 12:39, Mikal Hart <notifications@github.com>님이 작성:
