### ISSUE TITLE
disabling checksums for test purposes

### ISSUE THREAD

**Issue by arubli** [mikalhart/TinyGPSPlus#51]
I would like to know if it is possible to disable the checksum verification. I would like to send some test sentences to see if my project handles correctly some error conditions and if my DST subroutine is working. 
I am not a seasoned programmer... just sort of an advanced beginner

thank you

**Comment by mikalhart** [comment]
Hi.  Yeah, I think if you just replace this line:

`    if (checksum == parity)
`
with

`    if (true)
`
... it should work.
