### ISSUE TITLE
[Edited] Does TinyGPS++ support PPS? [was: change GPS Baud]

### ISSUE THREAD

**Issue by ajuancer** [mikalhart/TinyGPSPlus#53]
Hi! I have a GPS module with 5 Pins: GND, VCC, Rx, Tx & PPS. I know you can define `static const uint32_t GPSBaud = 4800; 
`  but I would like to know if it's also available to use the PPS pin.

**Comment by TD-er** [comment]
I still have to add a baud rate selector.
The functionality to use the PPS pin is built in, but it hasn't been tested yet.
Also make sure you do not connect the RX pin, or else there is a big chance the ESP will not boot properly after a restart.

**Comment by ajuancer** [comment]
?

**Comment by TD-er** [comment]
I did type a reply to it about what was just implemented in ESPeasy (my project, using this plugin) and what needs more testing.
Then I realized this wasn't the issue tracker of ESPeasy, so I removed my reply. (should have edited it)
So sorry for the confusion ;)

**Comment by bamapookie** [comment]
The PPS pin is not a serial interface.  It doesn't have a baud setting.  In my experience (with the Adafruit GBS board) you read the PPS pin through one of your digital inputs.  As soon as it goes high, that is the start of the second.  It is independent of the GPS messages being sent serially over the TX/RX pins.

Hope that helps.

**Comment by mikalhart** [comment]
FWIW, yes, you can change the baud rate in your sketch.

**Comment by sbonaime** [comment]
PPS means Pulse Per Second. It is one pulse every second which can validate date and time

**Comment by TD-er** [comment]
N.B. the PPS pin on most modules only will output a signal (of 1.000000 Hz, probably even less than 1 usec jitter) if the GPS has either a fix or a sufficient reliable knowledge of time.
