### ISSUE TITLE
RTK gps date problem

### ISSUE THREAD

**Issue by ykurban** [mikalhart/TinyGPSPlus#56]
connection with rtk gps does not produce date output.

example gps sentence: 

$GPGGA,151709.00,4008.28657638,N,02624.44704130,E,5,04,3.9,6.469,M,38.526,M,1.0,0206*43

**Comment by mikalhart** [comment]
$GPGGA sentences do not contain date info.  See http://aprs.gids.nl/nmea/.  If your unit is only transmitting $GPGGA (and not $GPRMC), then you will never get a date.
