### ISSUE TITLE
Do gps.location.rawLat().billionths need zero padding?

### ISSUE THREAD

**Issue by gregcope** [mikalhart/TinyGPSPlus#58]
Hi,

If `gps.location.rawLat().billionths` returns a smaller number do these not need to be padded?

Serial.println(gps.location.rawLat().billionths) here .. (and line 51 below)

https://github.com/mikalhart/TinyGPSPlus/blob/master/examples/KitchenSink/KitchenSink.ino#L46

**Comment by mikalhart** [comment]
I see your point.  If I was displaying these values after a decimal point, I would definitely need to left pad with zeros sometimes.  But I think in this format ("and xxx billionths") it should be pretty clear.
