### ISSUE TITLE
How can I get a signal accuracy ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [mikalhart/TinyGPSPlus#61]
Hello !

I am trying to find a function that can tell me the accuracy of the signal.

At first I thought that `TinyGPSPlus::distanceBetween()` should do the trick, but that function does something else.

Is it possible to get signal accuracy ?
Thank you !

**Comment by TD-er** [comment]
The HDOP value is some indicator on the accuracy of the received signal.
It is the standard deviation in meters. (99 if no fix)

**Comment by mikalhart** [comment]
Thanks @TD-er.  @GeorgeFlorian, are we good?
