### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by silardg** [mikalhart/TinyGPSPlus#64]
The examples all have default bauds of 4800, and it doesn't want to work. 
I have switched it to 9600 and it started working.

Is this a problem with just my neo-6m, that the default is 9600?

**Comment by detroy94** [comment]
I have the same problem kinda having issues with the library translating

**Comment by silardg** [comment]
I mean if you can fix it by just setting the baud to 9600, then this isn't really a bug.
I will close it but I would suggest creating a comment on the examples that if it doesn't work the baud should be changed

**Comment by silardg** [comment]
I would make a pull request, but there are already 5 pending...
