### ISSUE TITLE
getting raw sentence 

### ISSUE THREAD

**Issue by Toeedev** [mikalhart/TinyGPSPlus#73]
Is there a way to get raw sentence that is being parsed ? 
I want to parse sentence, check fix etc. but I want to log raw sentence to file.

**Comment by svdrummer** [comment]
I add my raw data file in the next line after feeding tinygps++

**Comment by mikalhart** [comment]
Yeah, me too.  This is a common request, but my consistent answer is that I do not want to take up valuable memory space storing        NMEA strings, especially on AVRs with small amounts of RAM.  This is easy enough to do outside TinyGPS++ if you need it.
