### ISSUE TITLE
Data is not getting generated here as you can see in the attachment, need your help please

### ISSUE THREAD

**Issue by NilothpalBhattacharya** [mikalhart/TinyGPSPlus#82]
Hi Mikal,
I am using NEO 6M GPS module and trying to check if the GPS module is responding properly.

Connected the four pins from UBLOX to an Arduino as follows:

GPS module ==> Arduino
GND ==> GND
TX ==> Digital pin (D3)
RX ==> Digital pin (D4)
Vcc ==> 3.3 V 

I am facing this issue , not sure if I am even able to fetch the correct data here. Please can you help here. 
![16019297710157489474404886056839](https://user-images.githubusercontent.com/10112571/95128958-ca8d3600-078c-11eb-8e06-9bba4e58548a.jpg)

![16019299747748523156553022917821](https://user-images.githubusercontent.com/10112571/95129124-1a6bfd00-078d-11eb-9020-c22eb22926b1.jpg)

![image](https://user-images.githubusercontent.com/10112571/95127580-c829dc80-078a-11eb-8fe7-a6cdfc1ed44e.png)

**Comment by mikalhart** [comment]
I think the UBlox baud rate should be set to 9600.

ss.begin(9600);

**Comment by NilothpalBhattacharya** [comment]
Thanks for coming back. Yes I have set the correct Baud rate . The default is 9600 for Neo 6M I hope. Is it okay if I can give you a call today please? Thankyou

**Comment by TD-er** [comment]
Just a simple question as I don't see it in your screenshot.
What pins on the Arduino board are assigned to the serial port you intent to use?
And remember to "cross" the RX and TX.
So TX on the GPS should be connected to RX on the serial port (the other one doesn't matter as isn't used)

Maybe for testing, you can also print every character you receive to help diagnose what's wrong here.

**Comment by mikalhart** [comment]
You can see in the screenshot on the right that large numbers of characters are being received, without any valid sentences and with lots of chksum fails.  This suggests that the wiring is correct but the baud rate is wrong.  Indeed, we can see in the left screen that the baud rate is set to 4800.

Agree with TD-er that printing out each character would be useful.

**Comment by NilothpalBhattacharya** [comment]
Sorry guys yesterday took the module outside under clear sky,it was working.just had to ensure the connection of pins were correct and the baud rate. Thankyou for your support.

**Comment by NilothpalBhattacharya** [comment]
I actually used Arduino Nano to interface all my sensors and Gps and LoRA module. So all that worked fine but it is an interesting work to learn from I realized.

**Comment by NilothpalBhattacharya** [comment]
> Just a simple question as I don't see it in your screenshot.
> What pins on the Arduino board are assigned to the serial port you intent to use?
> And remember to "cross" the RX and TX.
> So TX on the GPS should be connected to RX on the serial port (the other one doesn't matter as isn't used)
> 
> Maybe for testing, you can also print every character you receive to help diagnose what's wrong here.

I was using pin 7 as Rx, 6 as Tx of Arduino Nano

**Comment by svdrummer** [comment]
Should this be changed to CLOSED?
