### ISSUE TITLE
cardinal course calculation in FullExample.ino sketch

### ISSUE THREAD

**Issue by jurs** [mikalhart/TinyGPSPlus#9]
Instead of reading the gps.course.value() in the code of FullExample.ino:
printStr(gps.course.isValid() ? TinyGPSPlus::cardinal(gps.course.value()) : "**\* ", 6);
the course parameter must be given in degrees to get correct results:
printStr(gps.course.isValid() ? TinyGPSPlus::cardinal(gps.course.deg()) : "**\* ", 6);

**Comment by mikalhart** [comment]
Fixed in 1.0.0

**Comment by mikalhart** [comment]
Thanks @nolanholden.
