### ISSUE TITLE
Feature request: get last nmea sentence

### ISSUE THREAD

**Issue by denzen84** [mikalhart/TinyGPSPlus#94]
Need this feature to filter and redirect NMEA after TinyGPSplus parser. Buffer is private for the object and I can't access it. Of cource I can use my fork, but I don't want use this way. Thanks.

**Comment by mikalhart** [comment]
Hi @denzen84.  This is a common request, but I think storing NMEA for reuse should be done outside TinyGPS++.  See https://github.com/mikalhart/TinyGPSPlus/issues/73 for example.
